// https://docs.expo.dev/guides/using-eslint/
import eslintJs from '@eslint/js';
import { defineConfig } from 'eslint/config';
import prettierRecommended from 'eslint-plugin-prettier/recommended';
import simpleImportSort from 'eslint-plugin-simple-import-sort';
import globals from 'globals';
import { configs as tseslintConfigs } from 'typescript-eslint';

export default defineConfig([
  {
    name: '@blinkorb/ignores',
    ignores: [
      'node_modules',
      // expo
      '.expo',
      'android',
      'ios',
      'expo-env.d.ts',
      // next
      '.next',
      'out',
      'next-env.d.ts',
      // tests
      'coverage',
      // general builds stuff
      'build',
      'dist',
    ],
  },
  eslintJs.configs.recommended,
  {
    name: '@blinkorb/setup',
    languageOptions: {
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
  },
  {
    name: '@blinkorb/typescript-setup',
    files: ['**/*.{js,jsx,cjs,mjs,es,ts,tsx,mts,mtsx}'],
    extends: [tseslintConfigs.recommended],
    languageOptions: {
      parserOptions: {
        tsconfigRootDir: '/',
      },
    },
  },
  {
    name: '@blinkorb/imports',
    plugins: {
      'simple-import-sort': simpleImportSort,
    },
    rules: {
      'simple-import-sort/imports': 'error',
      'simple-import-sort/exports': 'error',
    },
  },
  {
    name: '@blinkorb/base-rules',
    rules: {
      strict: [2, 'global'],
      'no-duplicate-imports': [2, { includeExports: true }],
      eqeqeq: 2,
      'block-scoped-var': 2,
      'no-constant-condition': 2,
      'no-console': 2,
      'no-debugger': 2,
      'no-lonely-if': 2,
      'no-lone-blocks': 2,
      'no-nested-ternary': 2,
      'no-dupe-keys': 2,
      'no-extra-boolean-cast': 2,
      'no-irregular-whitespace': 2,
      'no-else-return': 2,
      'no-eval': 2,
      'no-multi-str': 2,
      'no-self-compare': 2,
      'no-useless-call': 2,
      'no-shadow-restricted-names': 2,
      'no-shadow': 0,
      'no-undef': 0,
      'no-undef-init': 2,
      'no-unreachable': 2,
      'no-unused-vars': [2, { varsIgnorePattern: '^_\\w' }],
      'no-use-before-define': 2,
      radix: 2,
      'no-fallthrough': 2,
      'default-case': 2,
      'no-var': 2,
      'no-unused-expressions': 2,
      camelcase: [
        2,
        {
          properties: 'always',
          allow: ['^UNSAFE_', 'call_id'],
        },
      ],
      '@typescript-eslint/no-explicit-any': 2,
      '@typescript-eslint/explicit-function-return-type': 0,
      '@typescript-eslint/member-delimiter-style': 0,
      '@typescript-eslint/type-annotation-spacing': 0,
      '@typescript-eslint/no-unused-vars': [2, { argsIgnorePattern: '^_' }],
      '@typescript-eslint/no-use-before-define': 2,
      '@typescript-eslint/no-shadow': 2,
      'no-restricted-globals': [
        'error',
        'URL',
        'window',
        'document',
        'history',
        'dispatchEvent',
        'require',
        'postMessage',
        'blur',
        'focus',
        'close',
        'frames',
        'self',
        'parent',
        'opener',
        'top',
        'length',
        'closed',
        'location',
        'origin',
        'name',
        'locationbar',
        'menubar',
        'personalbar',
        'scrollbars',
        'statusbar',
        'toolbar',
        'status',
        'frameElement',
        'navigator',
        'customElements',
        'external',
        'screen',
        'innerWidth',
        'innerHeight',
        'scrollX',
        'pageXOffset',
        'scrollY',
        'pageYOffset',
        'screenX',
        'screenY',
        'outerWidth',
        'outerHeight',
        'devicePixelRatio',
        'clientInformation',
        'screenLeft',
        'screenTop',
        'defaultStatus',
        'defaultstatus',
        'styleMedia',
        'onanimationend',
        'onanimationiteration',
        'onanimationstart',
        'onsearch',
        'ontransitionend',
        'onwebkitanimationend',
        'onwebkitanimationiteration',
        'onwebkitanimationstart',
        'onwebkittransitionend',
        'isSecureContext',
        'onabort',
        'onblur',
        'oncancel',
        'oncanplay',
        'oncanplaythrough',
        'onchange',
        'onclick',
        'onclose',
        'oncontextmenu',
        'oncuechange',
        'ondblclick',
        'ondrag',
        'ondragend',
        'ondragenter',
        'ondragleave',
        'ondragover',
        'ondragstart',
        'ondrop',
        'ondurationchange',
        'onemptied',
        'onended',
        'onerror',
        'onfocus',
        'oninput',
        'oninvalid',
        'onkeydown',
        'onkeypress',
        'onkeyup',
        'onload',
        'onloadeddata',
        'onloadedmetadata',
        'onloadstart',
        'onmousedown',
        'onmouseenter',
        'onmouseleave',
        'onmousemove',
        'onmouseout',
        'onmouseover',
        'onmouseup',
        'onmousewheel',
        'onpause',
        'onplay',
        'onplaying',
        'onprogress',
        'onratechange',
        'onreset',
        'onresize',
        'onscroll',
        'onseeked',
        'onseeking',
        'onselect',
        'onstalled',
        'onsubmit',
        'onsuspend',
        'ontimeupdate',
        'ontoggle',
        'onvolumechange',
        'onwaiting',
        'onwheel',
        'onauxclick',
        'ongotpointercapture',
        'onlostpointercapture',
        'onpointerdown',
        'onpointermove',
        'onpointerup',
        'onpointercancel',
        'onpointerover',
        'onpointerout',
        'onpointerenter',
        'onpointerleave',
        'onafterprint',
        'onbeforeprint',
        'onbeforeunload',
        'onhashchange',
        'onlanguagechange',
        'onmessage',
        'onmessageerror',
        'onoffline',
        'ononline',
        'onpagehide',
        'onpageshow',
        'onpopstate',
        'onrejectionhandled',
        'onstorage',
        'onunhandledrejection',
        'onunload',
        'performance',
        'stop',
        'open',
        'print',
        'captureEvents',
        'releaseEvents',
        'getComputedStyle',
        'matchMedia',
        'moveTo',
        'moveBy',
        'resizeTo',
        'resizeBy',
        'getSelection',
        'find',
        'createImageBitmap',
        'scroll',
        'scrollTo',
        'scrollBy',
        'onappinstalled',
        'onbeforeinstallprompt',
        'crypto',
        'ondevicemotion',
        'ondeviceorientation',
        'ondeviceorientationabsolute',
        'indexedDB',
        'webkitStorageInfo',
        'chrome',
        'visualViewport',
        'speechSynthesis',
        'webkitRequestFileSystem',
        'webkitResolveLocalFileSystemURL',
        'openDatabase',
        'setTimeout',
        'clearTimeout',
        'setInterval',
        'clearInterval',
        'requestAnimationFrame',
        'cancelAnimationFrame',
        'addEventListener',
        'removeEventListener',
      ],
      'prefer-const': 2,
    },
  },
  {
    name: '@blinkorb/typescript-overrides',
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      'no-undef': 'off',
      'no-unused-vars': 'off',
      'no-use-before-define': 'off',
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/member-delimiter-style': 'off',
      '@typescript-eslint/type-annotation-spacing': 'off',
      '@typescript-eslint/no-unused-vars': 'error',
      '@typescript-eslint/no-use-before-define': 'error',
      '@typescript-eslint/no-shadow': 'error',
    },
  },
  prettierRecommended,
  {
    name: '@blinkorb/formatting',
    rules: {
      curly: 2,
    },
  },
]);
